swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /signup:
    # binds a127 app logic to a route
    x-swagger-router-controller: signup-controller
    post:
      tags:
      - Signup
      description: Adds user data in database and returns method sucess or failure
      # used as the method name of the controller
      operationId: signup
      parameters:
        - name: user
          in: body
          description: user detail
          required: true
          schema:
            $ref: '#/definitions/SignupRequest'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SignupResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/SignupErrorResponse"

  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: 
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"


  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

  SignupRequest:
    description: Add a new user
    properties:
      firstname:
        type: string
        description: user's first name
      lastname:
        type: string
        description: user's last name
      email:
        type: string
        description: user's email id
      password:
        type: string
        description: user's password
    required:
      - firstname
      - lastname
      - email
      - password

  SignupResponse:
    required:
      - message
    properties:
      message:
        type: string

  SignupErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
